/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue May 16 04:05:10 GMT 2017
 */

package edu.osu.cs362;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TimeTable_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "edu.osu.cs362.TimeTable"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("java.vm.vendor", "Oracle Corporation");
    System.setProperty("java.specification.version", "1.8");
            System.setProperty("java.home", "C:\\Program Files\\Java\\jdk1.8.0_91\\jre");
                System.setProperty("user.home", "C:\\Users\\Gabe K");
            System.setProperty("java.awt.headless", "true");
                                System.setProperty("user.dir", "C:\\Users\\Gabe K\\Documents\\Programming\\CS362-001-SP17\\projects\\kauffmag\\assignment-3\\Calendar");
    System.setProperty("java.io.tmpdir", "C:\\Users\\GABEK~1\\AppData\\Local\\Temp\\");
    System.setProperty("awt.toolkit", "sun.awt.windows.WToolkit");
    System.setProperty("file.encoding", "Cp1252");
    System.setProperty("file.separator", "\\");
        System.setProperty("java.awt.graphicsenv", "sun.awt.Win32GraphicsEnvironment");
    System.setProperty("java.awt.printerjob", "sun.awt.windows.WPrinterJob");
    System.setProperty("java.class.path", "C:\\Users\\GABEK~1\\AppData\\Local\\Temp\\EvoSuite_pathingJar5488430348946858473.jar");
    System.setProperty("java.class.version", "52.0");
        System.setProperty("java.endorsed.dirs", "C:\\Program Files\\Java\\jdk1.8.0_91\\jre\\lib\\endorsed");
    System.setProperty("java.ext.dirs", "C:\\Program Files\\Java\\jdk1.8.0_91\\jre\\lib\\ext;C:\\Windows\\Sun\\Java\\lib\\ext");
    System.setProperty("java.library.path", "lib");
    System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment");
    System.setProperty("java.runtime.version", "1.8.0_91-b15");
    System.setProperty("java.specification.name", "Java Platform API Specification");
    System.setProperty("java.specification.vendor", "Oracle Corporation");
        System.setProperty("java.vendor", "Oracle Corporation");
    System.setProperty("java.vendor.url", "http://java.oracle.com/");
    System.setProperty("java.version", "1.8.0_91");
    System.setProperty("java.vm.info", "mixed mode");
    System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM");
    System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification");
    System.setProperty("java.vm.specification.vendor", "Oracle Corporation");
    System.setProperty("java.vm.specification.version", "1.8");
    System.setProperty("java.vm.version", "25.91-b15");
    System.setProperty("line.separator", "\r\n");
    System.setProperty("os.arch", "amd64");
    System.setProperty("os.name", "Windows 7");
    System.setProperty("os.version", "6.1");
    System.setProperty("path.separator", ";");
    System.setProperty("user.country", "US");
    System.setProperty("user.language", "en");
    System.setProperty("user.name", "Gabe K");
    System.setProperty("user.timezone", "America/Los_Angeles");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TimeTable_ESTest_scaffolding.class.getClassLoader() ,
      "edu.osu.cs362.TimeTable",
      "edu.osu.cs362.CalDay",
      "edu.osu.cs362.Appt"
    );
  } 

  private static void resetClasses() {
  }
}
