/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 05:28:35 GMT 2017
 */

package hw1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import hw1.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
      int[] intArray0 = null;
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      App.main(stringArray0);
      String string0 = " ";
      stringArray0[2] = string0;
      String string1 = "";
      stringArray0[3] = string1;
      App.main(stringArray0);
      app0.sort(intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      int[] intArray0 = new int[0];
      app0.sort(intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      App app0 = new App();
      int[] intArray0 = new int[4];
      intArray0[0] = (-368);
      intArray0[1] = (-1);
      intArray0[2] = 0;
      intArray0[3] = 0;
      app0.sort(intArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      App app0 = new App();
      String[] stringArray0 = null;
      App.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      App app0 = new App();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "'<E ;?RN2ga?";
      // Undeclared exception!
      try { 
        app0.sort((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("hw1.App", e);
      }
  }
}
